# Generated by Django 4.1.1 on 2023-09-14 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.TextField()),
                ('Status', models.CharField(max_length=10)),
                ('When', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
